[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"

[fuzz]
runs = 256

[etherscan]
mainnet = { key = "YOUR_ETHERSCAN_API_KEY" }

[rpc_endpoints]
mainnet = "https://eth-mainnet.public.blastapi.io"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
